# Generated by Django 4.2.30 on 2026-08-22 22:22

from django.db import migrations, models
import django.db.models.deletion


def repair_existing_data(apps, schema_editor):
    Category = apps.get_model('finance', 'Category')
    Period = apps.get_model('finance', 'Period')
    Category.objects.filter(group='LIFESTYLE').update(group='Gastos')
    for period in Period.objects.filter(start_date__gt=models.F('end_date')):
        period.start_date, period.end_date = period.end_date, period.start_date
        period.save(update_fields=['start_date', 'end_date'])
    active = Period.objects.filter(is_active=True).order_by('-start_date', '-id')
    if active.count() > 1:
        active.exclude(pk=active.first().pk).update(is_active=False)
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT setval(pg_get_serial_sequence('finance_category', 'id'), COALESCE((SELECT MAX(id) FROM finance_category), 1), true)")


def install_transaction_period_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('''
            CREATE OR REPLACE FUNCTION finance_transaction_period_check() RETURNS trigger AS $$
            BEGIN
                IF NEW.budget_item_id IS NOT NULL AND NOT EXISTS (
                    SELECT 1 FROM finance_budget_item b
                    JOIN finance_period p ON p.id = b.period_id
                    WHERE b.id = NEW.budget_item_id
                    AND NEW.date BETWEEN p.start_date AND p.end_date
                ) THEN
                    RAISE EXCEPTION 'transaction date must belong to its budget item period';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            DROP TRIGGER IF EXISTS finance_transaction_period_guard ON finance_transaction;
            CREATE TRIGGER finance_transaction_period_guard
            BEFORE INSERT OR UPDATE OF budget_item_id, date ON finance_transaction
            FOR EACH ROW EXECUTE FUNCTION finance_transaction_period_check();
        ''')


def remove_transaction_period_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('DROP TRIGGER IF EXISTS finance_transaction_period_guard ON finance_transaction; DROP FUNCTION IF EXISTS finance_transaction_period_check();')


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('BANK', 'Bank statement'), ('CREDIT_CARD', 'Credit card statement'), ('NOTIFICATION', 'Notification')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('account_reference', models.CharField(blank=True, max_length=100)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('parser_version', models.CharField(default='1', max_length=40)),
                ('status', models.CharField(choices=[('STAGED', 'Staged'), ('COMMITTED', 'Committed'), ('DISCARDED', 'Discarded')], default='STAGED', max_length=20)),
            ],
            options={
                'db_table': 'finance_import_batch',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.RunPython(repair_existing_data, migrations.RunPython.noop),
        migrations.RenameIndex(
            model_name='budgetitem',
            new_name='budget_item_period_idx',
            old_name='finance_budget_item_period_id_idx',
        ),
        migrations.RenameIndex(
            model_name='budgetitem',
            new_name='budget_item_category_idx',
            old_name='finance_budget_item_category_id_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='category_name_idx',
            old_name='finance_category_name_idx',
        ),
        migrations.RenameIndex(
            model_name='period',
            new_name='period_start_date_idx',
            old_name='finance_period_start_date_idx',
        ),
        migrations.RenameIndex(
            model_name='period',
            new_name='period_end_date_idx',
            old_name='finance_period_end_date_idx',
        ),
        migrations.RenameIndex(
            model_name='stagingcctransaction',
            new_name='staging_cc_processed_idx',
            old_name='finance_staging_cc_is_processed_idx',
        ),
        migrations.RenameIndex(
            model_name='stagingcctransaction',
            new_name='staging_cc_original_date_idx',
            old_name='finance_staging_cc_original_date_idx',
        ),
        migrations.RenameIndex(
            model_name='stagingcctransaction',
            new_name='staging_cc_category_idx',
            old_name='finance_staging_cc_category_id_idx',
        ),
        migrations.RenameIndex(
            model_name='stagingtransaction',
            new_name='staging_processed_idx',
            old_name='finance_staging_transaction_is_processed_idx',
        ),
        migrations.RenameIndex(
            model_name='stagingtransaction',
            new_name='staging_original_date_idx',
            old_name='finance_staging_transaction_original_date_idx',
        ),
        migrations.RenameIndex(
            model_name='stagingtransaction',
            new_name='staging_category_idx',
            old_name='finance_staging_transaction_category_id_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_date_idx',
            old_name='finance_transaction_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_budget_item_idx',
            old_name='finance_transaction_budget_item_id_idx',
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('AhorroeInversion', 'Ahorro e Inversión'), ('Alimentación', 'Alimentación'), ('Cuenta', 'Cuenta'), ('CuentaVina', 'Cuenta Viña'), ('Deuda', 'Deuda'), ('Gastos', 'Gastos'), ('GastosExtraordinarios', 'Gastos Extraordinarios'), ('IngresoFijo', 'Ingreso Fijo'), ('IngresoVariableExtra', 'Ingreso Variable / Extra'), ('Lujo', 'Lujo'), ('Pension', 'Pension'), ('Personal', 'Personal'), ('Transporte', 'Transporte'), ('ViviendaHogar', 'Vivienda / Hogar')], db_column='"group"', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='period',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stagingcctransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stagingtransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='finance_period_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='finance_period_single_active'),
        ),
        migrations.AddField(
            model_name='stagingcctransaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staging_cc_transactions', to='finance.importbatch'),
        ),
        migrations.AddField(
            model_name='stagingtransaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staging_transactions', to='finance.importbatch'),
        ),
        migrations.AddIndex(
            model_name='stagingcctransaction',
            index=models.Index(fields=['batch', 'is_processed'], name='staging_cc_batch_processed_idx'),
        ),
        migrations.AddIndex(
            model_name='stagingtransaction',
            index=models.Index(fields=['batch', 'is_processed'], name='staging_batch_processed_idx'),
        ),
        migrations.RunPython(install_transaction_period_trigger, remove_transaction_period_trigger),
    ]
