# Generated by Django 4.2.30 on 2026-08-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transactionsplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantRuleProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual creation'), ('SUGGESTION', 'From accepted suggestion'), ('IMPORT', 'Imported from backup')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_description', models.TextField(blank=True, help_text='Why this rule was created')),
                ('evidence_transactions', models.PositiveIntegerField(default=0, help_text='Number of transactions used as evidence')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='finance.merchantrule')),
            ],
            options={
                'db_table': 'finance_merchant_rule_provenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_confidence', models.FloatField(default=0.0, help_text='Confidence score 0.0-1.0')),
                ('suggested_source', models.CharField(default='merchant_rule', help_text='merchant_rule or history', max_length=50)),
                ('event', models.CharField(choices=[('SHOWN', 'Suggestion shown to user'), ('ACCEPTED', 'User accepted suggestion'), ('REJECTED', 'User rejected suggestion'), ('DISMISSED', 'User dismissed suggestion'), ('EDITED', 'User edited suggested category'), ('RULE_CREATED', 'User created a rule from suggestion')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_at', models.DateTimeField(auto_now=True)),
                ('staging_cc_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_feedback', to='finance.stagingcctransaction')),
                ('staging_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_feedback', to='finance.stagingtransaction')),
                ('suggested_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_feedback_received', to='finance.category')),
                ('user_action_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_feedback_user_actions', to='finance.category')),
            ],
            options={
                'db_table': 'finance_suggestion_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event'], name='sugg_feedback_event_idx'), models.Index(fields=['created_at'], name='sugg_feedback_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='suggestionfeedback',
            constraint=models.CheckConstraint(check=models.Q(('staging_transaction__isnull', False), ('staging_cc_transaction__isnull', False), _connector='OR'), name='suggestion_feedback_has_staging_source'),
        ),
    ]
