from django.urls import path
from finance.views import (
    DashboardView,
    BudgetMonthListView,
    BudgetMonthCreateView,
    BudgetMonthUpdateView,
    BudgetMonthDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    BudgetItemCreateView,
    BudgetItemUpdateView,
    BudgetItemDeleteView,
    TransactionCreateView,
    TransactionUpdateView,
    TransactionDeleteView,
    StatementUploadView,
    StagingReviewView,
)

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('months/', BudgetMonthListView.as_view(), name='budget-month-list'),
    path('months/create/', BudgetMonthCreateView.as_view(), name='budget-month-create'),
    path('months/<int:pk>/update/', BudgetMonthUpdateView.as_view(), name='budget-month-update'),
    path('months/<int:pk>/delete/', BudgetMonthDeleteView.as_view(), name='budget-month-delete'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/create/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('budget-items/create/', BudgetItemCreateView.as_view(), name='budget-item-create'),
    path('budget-items/<int:pk>/update/', BudgetItemUpdateView.as_view(), name='budget-item-update'),
    path('budget-items/<int:pk>/delete/', BudgetItemDeleteView.as_view(), name='budget-item-delete'),
    path('transactions/create/', TransactionCreateView.as_view(), name='transaction-create'),
    path('transactions/<int:pk>/update/', TransactionUpdateView.as_view(), name='transaction-update'),
    path('transactions/<int:pk>/delete/', TransactionDeleteView.as_view(), name='transaction-delete'),
    path('upload-statement/', StatementUploadView.as_view(), name='statement-upload'),
    path('staging-review/', StagingReviewView.as_view(), name='staging-review'),
]
